# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgbmGVLwQj-9DAdtLUMsnDS0IWRRrTKo
"""

!pip install streamlit

#!/usr/bin/env python3
"""
Criteria Selection Dashboard - Streamlit Web Application
Converted from Jupyter Notebook
"""

import streamlit as st
import pandas as pd
import numpy as np
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
import os
from datetime import datetime
import pyomo.environ as pyo
from pyomo.opt import SolverFactory, TerminationCondition
import re
from typing import Dict, List, Tuple, Any
import io

# ================================================================
# PAGE CONFIGURATION
# ================================================================
st.set_page_config(
    page_title="Criteria Selection Dashboard",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for better styling
st.markdown("""
    <style>
    .main {
        padding: 2rem;
    }
    .stButton>button {
        width: 100%;
    }
    .success-box {
        padding: 1rem;
        background-color: #d4edda;
        border-radius: 0.5rem;
        border-left: 4px solid #28a745;
    }
    .info-box {
        padding: 1rem;
        background-color: #d1ecf1;
        border-radius: 0.5rem;
        border-left: 4px solid #17a2b8;
    }
    .warning-box {
        padding: 1rem;
        background-color: #fff3cd;
        border-radius: 0.5rem;
        border-left: 4px solid #ffc107;
    }
    </style>
""", unsafe_allow_html=True)

# ================================================================
# EXCEL PROCESSOR CLASS (Your existing code - NO CHANGES)
# ================================================================
class MCDMExcelProcessor:
    """
    A generic processor for MCDM Excel templates that reads and processes
    multiple sheets without hardcoding values.
    """

    def __init__(self, excel_file):
        """Initialize with Excel file (file-like object or path)."""
        self.excel_file = pd.ExcelFile(excel_file)
        self.sheet_names = self.excel_file.sheet_names

        # Initialize storage for all arrays and tracking
        self.criteria = []
        self.criteria_ids = []
        self.criteria_names = []
        self.alternatives = []
        self.experts = []
        self.num_criteria = 0
        self.num_alternatives = 0
        self.num_experts = 0

        # Arrays to be created
        self.c_values = None
        self.o_values = None
        self.m_values = None
        self.s_values = None
        self.ce_values = None
        self.a_values = None
        self.cc_values = None
        self.r_mat = None

        # Track criteria marked as "below"
        self.below_criteria = {
            'completeness': [],
            'measurability': [],
            'cognitive_coherence': [],
            'alignment': [],
            'cost_effectiveness': [],
            'sensitivity': []
        }

        # Criterion types for normalization
        self.criterion_types = {}

    def extract_basic_info(self):
        """Extract basic information like criteria, alternatives, and experts from the Excel."""
        # First, try to get criteria from Step1-Completeness
        criteria_found = False
        for sheet_name in self.sheet_names:
            if 'Step1' in sheet_name or 'Completeness' in sheet_name:
                df = pd.read_excel(self.excel_file, sheet_name=sheet_name)

                if 'Criterion ID' in df.columns and 'Criterion Name' in df.columns:
                    self.criteria_ids = df['Criterion ID'].dropna().tolist()
                    self.criteria_names = df['Criterion Name'].dropna().tolist()
                    self.criteria = self.criteria_ids if self.criteria_ids else self.criteria_names
                    criteria_found = True
                    break
                elif 'Criterion' in df.columns:
                    self.criteria = df['Criterion'].dropna().unique().tolist()
                    self.criteria_ids = self.criteria
                    self.criteria_names = self.criteria
                    criteria_found = True
                    break

        # Try to find alternatives from Step6_Sensitivity sheet
        alternatives_found = False
        for sheet_name in self.sheet_names:
            if 'Step6' in sheet_name or 'Sensitivity' in sheet_name:
                df = pd.read_excel(self.excel_file, sheet_name=sheet_name, header=None)

                for idx, row in df.iterrows():
                    for col_idx, cell in enumerate(row):
                        if str(cell).strip() == 'Alternative':
                            alt_values = []
                            for next_idx in range(idx + 1, min(idx + 10, len(df))):
                                alt_value = df.iloc[next_idx, col_idx]
                                if pd.notna(alt_value) and str(alt_value).strip():
                                    if 'Expert' in str(alt_value) or 'Matrix' in str(alt_value):
                                        break
                                    alt_values.append(str(alt_value).strip())

                            if alt_values:
                                self.alternatives = alt_values
                                alternatives_found = True
                                break
                    if alternatives_found:
                        break
                if alternatives_found:
                    break

        # Count experts
        expert_count = 0
        for sheet_name in self.sheet_names:
            if 'Step6' in sheet_name or 'Sensitivity' in sheet_name:
                df = pd.read_excel(self.excel_file, sheet_name=sheet_name, header=None)
                for idx, row in df.iterrows():
                    row_str = ' '.join(str(cell) for cell in row if pd.notna(cell))
                    if 'Expert' in row_str and ('Decision Matrix' in row_str or 'Matrix' in row_str):
                        expert_count += 1
                break

        self.num_experts = expert_count if expert_count > 0 else 3
        self.num_criteria = len(self.criteria)
        self.num_alternatives = len(self.alternatives)

        self.identify_criterion_types()

    def identify_criterion_types(self):
        """Identify whether criteria are benefits or costs."""
        cost_keywords = ['cost', 'emission', 'impact', 'time', 'requirement', 'risk', 'complexity']

        if self.criteria_names and len(self.criteria_names) == len(self.criteria_ids):
            for crit_id, crit_name in zip(self.criteria_ids, self.criteria_names):
                name_lower = crit_name.lower()
                is_cost = any(keyword in name_lower for keyword in cost_keywords)
                self.criterion_types[crit_id] = 'cost' if is_cost else 'benefit'
        else:
            for criterion in self.criteria:
                criterion_lower = criterion.lower()
                is_cost = any(keyword in criterion_lower for keyword in cost_keywords)
                self.criterion_types[criterion] = 'cost' if is_cost else 'benefit'

    def find_sheet_by_keyword(self, *keywords):
        """Find sheet name containing all specified keywords."""
        for sheet_name in self.sheet_names:
            sheet_lower = sheet_name.lower()
            if all(keyword.lower() in sheet_lower for keyword in keywords):
                return sheet_name
        return None

    def process_all_sheets(self):
        """Process all sheets in sequence."""
        self.extract_basic_info()

        # Process each step
        self.process_step1_completeness()
        self.process_step2_objectivity()
        self.process_step3_measurability()
        self.process_step4_distinctiveness()
        self.process_step6_sensitivity()
        self.process_step7_cost_effectiveness()
        self.process_step8_alignment()
        self.process_step9_cognitive_coherence()

        return self.get_results()

    def process_step1_completeness(self):
        """Process Step1-Completeness sheet."""
        sheet_name = self.find_sheet_by_keyword('Step1', 'Completeness')
        if not sheet_name:
            return

        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)

        if 'Average' in df.columns:
            self.c_values = df['Average'].dropna().values
        elif 'Avg' in df.columns:
            self.c_values = df['Avg'].dropna().values

        if 'Status' in df.columns:
            status_col = df['Status'].fillna('').astype(str)
            below_mask = status_col.str.lower() == 'below'
            if 'Criterion ID' in df.columns:
                self.below_criteria['completeness'] = df.loc[below_mask, 'Criterion ID'].tolist()

    def process_step2_objectivity(self):
        """Process Step2_Objectivity sheet."""
        sheet_name = self.find_sheet_by_keyword('Step2', 'Objectivity')
        if not sheet_name:
            return

        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)

        if 'Consensus' in df.columns:
            self.o_values = df['Consensus'].dropna().values
        elif 'Consensus Score' in df.columns:
            self.o_values = df['Consensus Score'].dropna().values

    def process_step3_measurability(self):
        """Process Step3_Measurability sheet."""
        sheet_name = self.find_sheet_by_keyword('Step3', 'Measurability')
        if not sheet_name:
            return

        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)

        if 'Average' in df.columns:
            self.m_values = df['Average'].dropna().values
        elif 'Avg' in df.columns:
            self.m_values = df['Avg'].dropna().values

        if 'Status' in df.columns:
            status_col = df['Status'].fillna('').astype(str)
            below_mask = status_col.str.lower() == 'below'
            if 'Criterion ID' in df.columns:
                self.below_criteria['measurability'] = df.loc[below_mask, 'Criterion ID'].tolist()

    def process_step4_distinctiveness(self):
        """Process Step4_Distinctiveness sheet for correlation analysis."""
        sheet_name = self.find_sheet_by_keyword('Step4', 'Distinctiveness')
        if not sheet_name:
            return

        decision_matrices = self.read_decision_matrices(sheet_name)

        if decision_matrices:
            correlations = []
            for expert_name, matrix in decision_matrices.items():
                corr_matrix = matrix.corr()
                correlations.append(corr_matrix)

            if correlations:
                avg_correlation = sum(correlations) / len(correlations)
                self.r_mat = avg_correlation.abs().values

    def process_step6_sensitivity(self):
        """Process Step6_Sensitivity sheet using Monte Carlo simulation."""
        sheet_name = self.find_sheet_by_keyword('Step6', 'Sensitivity')
        if not sheet_name:
            return

        decision_matrices = self.read_decision_matrices(sheet_name)

        if not decision_matrices:
            return

        normalized_matrices = {}
        for expert_name, matrix in decision_matrices.items():
            normalized_matrices[expert_name] = self.normalize_matrix(matrix)

        num_simulations = 1000
        num_criteria = len(self.criteria)
        random_weights = np.random.dirichlet(np.ones(num_criteria), num_simulations)

        sensitivity_results = {}
        for expert_name, norm_mat in normalized_matrices.items():
            elasticities = pd.DataFrame(index=norm_mat.columns,
                                       columns=range(num_simulations))

            for i, weights in enumerate(random_weights):
                scores = np.dot(norm_mat.values, weights)
                for j, criterion in enumerate(norm_mat.columns):
                    w = weights[j]
                    elasticity = (norm_mat[criterion] * w).sum() / scores.sum()
                    elasticities.loc[criterion, i] = elasticity

            sensitivity_results[expert_name] = elasticities.mean(axis=1)

        if sensitivity_results:
            average_elasticity = pd.DataFrame(sensitivity_results).mean(axis=1)
            self.s_values = average_elasticity.values

            threshold = 0.05
            for i, value in enumerate(self.s_values):
                if value < threshold:
                    if i < len(self.criteria):
                        criterion = self.criteria[i]
                        if criterion not in self.below_criteria['sensitivity']:
                            self.below_criteria['sensitivity'].append(criterion)

    def process_step7_cost_effectiveness(self):
        """Process Step7_Cost_effectiveness sheet."""
        sheet_name = self.find_sheet_by_keyword('Step7', 'Cost')
        if not sheet_name:
            return

        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)

        costs = np.zeros(self.num_criteria)
        expert_ratings = np.zeros((self.num_criteria, self.num_experts))

        crit_col = 'Criterion ID' if 'Criterion ID' in df.columns else 'Criterion'
        cost_col = None
        for col in df.columns:
            if 'Cost' in str(col) or 'Evaluation Cost' in str(col):
                cost_col = col
                break

        expert_cols = [col for col in df.columns if 'Expert' in str(col) or 'Rating' in str(col)]

        if crit_col and cost_col:
            crit_to_idx = {crit: i for i, crit in enumerate(self.criteria)}

            for _, row in df.iterrows():
                if pd.notna(row[crit_col]):
                    criterion = str(row[crit_col])
                    if criterion in crit_to_idx:
                        idx = crit_to_idx[criterion]

                        if pd.notna(row[cost_col]):
                            costs[idx] = float(row[cost_col])

                        for j, expert_col in enumerate(expert_cols[:self.num_experts]):
                            if pd.notna(row[expert_col]):
                                expert_ratings[idx, j] = float(row[expert_col])

        if np.any(costs > 0) and np.any(expert_ratings > 0):
            average_scores = np.mean(expert_ratings, axis=1)
            effectiveness_weights = np.ones(self.num_criteria)
            for i in range(self.num_criteria):
                if average_scores[i] > 0:
                    effectiveness_weights[i] = 1 - (average_scores[i] - 5) / 5
                    effectiveness_weights[i] = max(0.1, min(2.0, effectiveness_weights[i]))

            self.ce_values = costs * effectiveness_weights

        if 'Status' in df.columns:
            status_col = df['Status'].fillna('').astype(str)
            below_mask = status_col.str.lower() == 'below'
            if crit_col:
                self.below_criteria['cost_effectiveness'] = df.loc[below_mask, crit_col].tolist()

    def process_step8_alignment(self):
        """Process Step8_Alignment sheet."""
        sheet_name = self.find_sheet_by_keyword('Step8', 'Alignment')
        if not sheet_name:
            return

        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)

        if 'Average' in df.columns:
            self.a_values = df['Average'].dropna().values
        elif 'Avg' in df.columns:
            self.a_values = df['Avg'].dropna().values

        if 'Status' in df.columns:
            status_col = df['Status'].fillna('').astype(str)
            below_mask = status_col.str.lower() == 'below'
            if 'Criterion ID' in df.columns:
                self.below_criteria['alignment'] = df.loc[below_mask, 'Criterion ID'].tolist()

    def process_step9_cognitive_coherence(self):
        """Process Step9_Cognitive_Coherence sheet."""
        sheet_name = self.find_sheet_by_keyword('Step9', 'Cognitive', 'Coherence')
        if not sheet_name:
            return

        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)

        if 'Average' in df.columns:
            self.cc_values = df['Average'].dropna().values
        elif 'Avg' in df.columns:
            self.cc_values = df['Avg'].dropna().values

        if 'Status' in df.columns:
            status_col = df['Status'].fillna('').astype(str)
            below_mask = status_col.str.lower() == 'below'
            if 'Criterion ID' in df.columns:
                self.below_criteria['cognitive_coherence'] = df.loc[below_mask, 'Criterion ID'].tolist()

    def read_decision_matrices(self, sheet_name):
        """Read decision matrices from a sheet."""
        df_full = pd.read_excel(self.excel_file, sheet_name=sheet_name, header=None)
        decision_matrices = {}

        expert_markers = []
        for idx, row in df_full.iterrows():
            row_str = ' '.join(str(cell) for cell in row if pd.notna(cell))
            if 'Expert' in row_str and ('Decision Matrix' in row_str or 'Matrix' in row_str):
                match = re.search(r'Expert\s*(\d+)', row_str)
                if match:
                    expert_num = int(match.group(1))
                    expert_markers.append((idx, f'Expert {expert_num}'))

        if expert_markers:
            for i, (start_row, expert_name) in enumerate(expert_markers):
                if i < len(expert_markers) - 1:
                    end_row = expert_markers[i + 1][0] - 1
                else:
                    end_row = start_row + 20

                try:
                    df_matrix = pd.read_excel(self.excel_file, sheet_name=sheet_name,
                                            skiprows=start_row + 1,
                                            nrows=min(end_row - start_row - 1, 10))

                    if not df_matrix.empty:
                        alt_col = None
                        for col in df_matrix.columns:
                            if 'Alternative' in str(col) or 'Option' in str(col):
                                alt_col = col
                                break

                        if alt_col is None and not df_matrix.columns[0].startswith('Unnamed'):
                            alt_col = df_matrix.columns[0]

                        if alt_col:
                            valid_alts = df_matrix[alt_col].dropna()
                            valid_alts = [alt for alt in valid_alts if
                                        isinstance(alt, str) and
                                        len(alt) > 5 and
                                        'Expert' not in alt and
                                        'Matrix' not in alt]

                            if valid_alts:
                                criteria_cols = []
                                for col in df_matrix.columns:
                                    if col != alt_col and not str(col).startswith('Unnamed'):
                                        if col in self.criteria or col in self.criteria_ids or col in self.criteria_names:
                                            criteria_cols.append(col)

                                if not criteria_cols:
                                    criteria_cols = [col for col in df_matrix.columns
                                                   if col != alt_col and
                                                   not str(col).startswith('Unnamed')]

                                if criteria_cols:
                                    matrix_data = df_matrix.loc[df_matrix[alt_col].isin(valid_alts), criteria_cols]
                                    matrix_data.index = valid_alts[:len(matrix_data)]

                                    for col in matrix_data.columns:
                                        matrix_data[col] = pd.to_numeric(matrix_data[col], errors='coerce')

                                    matrix_data = matrix_data.dropna(how='all').dropna(axis=1, how='all')

                                    if not matrix_data.empty:
                                        decision_matrices[expert_name] = matrix_data

                except Exception as e:
                    continue

        return decision_matrices

    def normalize_matrix(self, matrix):
        """Normalize matrix with benefit/cost logic."""
        norm = matrix.copy()
        for col in matrix.columns:
            max_val = matrix[col].max()
            min_val = matrix[col].min()

            if max_val == min_val:
                norm[col] = 1.0
            elif self.criterion_types.get(col, 'benefit') == 'benefit':
                norm[col] = (matrix[col] - min_val) / (max_val - min_val)
            else:
                norm[col] = (max_val - matrix[col]) / (max_val - min_val)

        return norm

    def get_results(self):
        """Return all processed results."""
        results = {
            'criteria': self.criteria,
            'criteria_ids': self.criteria_ids,
            'criteria_names': self.criteria_names,
            'alternatives': self.alternatives,
            'num_criteria': self.num_criteria,
            'num_alternatives': self.num_alternatives,
            'num_experts': self.num_experts,
            'c_values': self.c_values,
            'o_values': self.o_values,
            'm_values': self.m_values,
            's_values': self.s_values,
            'ce_values': self.ce_values,
            'a_values': self.a_values,
            'cc_values': self.cc_values,
            'r_mat': self.r_mat,
            'below_criteria': self.below_criteria,
            'criterion_types': self.criterion_types
        }

        return results

# ================================================================
# TEMPLATE GENERATOR FUNCTIONS (Your existing code - NO CHANGES)
# ================================================================
def create_excel_template(config, thresholds):
    """Create the MCDM Excel template"""
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    alternatives = [f"Alternative {i+1}" for i in range(config['alternatives'])]

    # Create all sheets
    create_instructions_sheet(wb, config, thresholds)
    create_step1_completeness(wb, config, thresholds)
    create_step2_objectivity(wb, config)
    create_step3_measurability(wb, config, thresholds)
    create_step4_distinctiveness(wb, config, alternatives)
    create_step5_parsimony(wb, config)
    create_step6_sensitivity(wb, config, alternatives)
    create_step7_cost_effectiveness(wb, config, thresholds)
    create_step8_alignment(wb, config, thresholds)
    create_step9_cognitive_coherence(wb, config, thresholds)

    return wb

# [Include all your sheet creation functions here - I'll abbreviate for space]
def create_instructions_sheet(wb, config, thresholds):
    ws = wb.create_sheet("Instructions")
    instructions = [
        ["CRITERIA SELECTION DASHBOARD - EXCEL TEMPLATE"],
        [],
        ["CONFIGURATION SUMMARY:"],
        [f"Alternatives: {config['alternatives']}", f"Experts: {config['experts']}", f"Criteria: {config['criteria']}"],
        [f"Target Range: ω={config['omega']}, ζ={config['zeta']}"],
        [],
        ["Fill in the YELLOW highlighted cells with your data"],
    ]
    for row_idx, row_data in enumerate(instructions, 1):
        for col_idx, value in enumerate(row_data, 1):
            ws.cell(row=row_idx, column=col_idx, value=value)

def create_step1_completeness(wb, config, thresholds):
    ws = wb.create_sheet("Step1_Completeness")
    ws['A1'] = "Step 1: Completeness Evaluation"
    ws['A2'] = "Rate how well each criterion covers the decision aspect (1-10 scale)"

    row = 5
    headers = ["Criterion ID", "Criterion Name"]
    for e in range(config['experts']):
        headers.append(f"Expert_{e+1}")
    headers.extend(["Average", "Status"])

    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=row, column=col_idx, value=header)
        cell.font = Font(bold=True)

    for i in range(config['criteria']):
        row_num = 6 + i
        ws.cell(row=row_num, column=1, value=f"C{i+1}")
        ws.cell(row=row_num, column=2, value=f"Criterion {i+1}")

        for e in range(config['experts']):
            cell = ws.cell(row=row_num, column=3+e)
            cell.fill = PatternFill(start_color="FFF2CC", end_color="FFF2CC", fill_type="solid")

        first_expert_col = get_column_letter(3)
        last_expert_col = get_column_letter(2 + config['experts'])
        avg_col = get_column_letter(3 + config['experts'])

        avg_cell = ws.cell(row=row_num, column=3 + config['experts'])
        avg_cell.value = f'=IFERROR(AVERAGE({first_expert_col}{row_num}:{last_expert_col}{row_num}),"")'

        status_cell = ws.cell(row=row_num, column=4 + config['experts'])
        status_cell.value = f'=IF({avg_col}{row_num}="","",IF({avg_col}{row_num}>={thresholds["completeness"]},"Meets","Below"))'

def create_step2_objectivity(wb, config):
    ws = wb.create_sheet("Step2_Objectivity")
    ws['A1'] = "Step 2: Objectivity Classification"
    # Similar implementation...
    pass

def create_step3_measurability(wb, config, thresholds):
    ws = wb.create_sheet("Step3_Measurability")
    ws['A1'] = "Step 3: Measurability Assessment"
    # Similar implementation...
    pass

def create_step4_distinctiveness(wb, config, alternatives):
    ws = wb.create_sheet("Step4_Distinctiveness")
    ws['A1'] = "Step 4: Distinctiveness Analysis"
    # Similar implementation...
    pass

def create_step5_parsimony(wb, config):
    ws = wb.create_sheet("Step5_Parsimony")
    ws['A1'] = "Step 5: Parsimony Configuration"
    # Similar implementation...
    pass

def create_step6_sensitivity(wb, config, alternatives):
    ws = wb.create_sheet("Step6_Sensitivity")
    ws['A1'] = "Step 6: Sensitivity Analysis"
    # Similar implementation...
    pass

def create_step7_cost_effectiveness(wb, config, thresholds):
    ws = wb.create_sheet("Step7_Cost_Effectiveness")
    ws['A1'] = "Step 7: Cost-Effectiveness Evaluation"
    # Similar implementation...
    pass

def create_step8_alignment(wb, config, thresholds):
    ws = wb.create_sheet("Step8_Alignment")
    ws['A1'] = "Step 8: Alignment Assessment"
    # Similar implementation...
    pass

def create_step9_cognitive_coherence(wb, config, thresholds):
    ws = wb.create_sheet("Step9_Cognitive_Coherence")
    ws['A1'] = "Step 9: Cognitive Coherence Evaluation"
    # Similar implementation...
    pass

# ================================================================
# OPTIMIZATION MODEL (Your existing code - NO CHANGES)
# ================================================================
def build_optimization_model_with_weights(results, weights):
    """Build and solve the optimization model with custom weights"""
    I = list(range(1, results['num_criteria'] + 1))

    # Extract weights
    w1 = weights['w1']
    w2 = weights['w2']
    w3 = weights['w3']
    w4 = weights['w4']
    w5 = weights['w5']
    w6 = weights['w6']
    w7 = weights['w7']
    w8 = weights['w8']
    w9 = weights['w9']

    w5_minus = w5 / 2
    w5_plus = w5 / 2

    omega, zeta = 5, 9
    nI = len(I)

    # Data dictionaries
    c = {i: results['c_values'][i-1] if results['c_values'] is not None else 5.0 for i in I}
    m = {i: results['m_values'][i-1] if results['m_values'] is not None else 5.0 for i in I}
    s = {i: results['s_values'][i-1] if results['s_values'] is not None else 0.1 for i in I}
    ce = {i: results['ce_values'][i-1] if results['ce_values'] is not None else 1000.0 for i in I}
    a = {i: results['a_values'][i-1] if results['a_values'] is not None else 5.0 for i in I}
    cc = {i: results['cc_values'][i-1] if results['cc_values'] is not None else 5.0 for i in I}
    o = {i: results['o_values'][i-1] if results['o_values'] is not None else 0.5 for i in I}

    if results['r_mat'] is not None:
        r = {(i, j): results['r_mat'][i-1][j-1] for i in I for j in I if i < j}
    else:
        r = {(i, j): 0.0 for i in I for j in I if i < j}

    tot_c = sum(c.values())
    tot_m = sum(m.values())
    tot_a = sum(a.values())
    tot_cc = sum(cc.values())
    tot_s = sum(s.values())
    tot_ce = sum(ce.values())

    # Build model
    M = pyo.ConcreteModel()
    M.I = pyo.Set(initialize=I)
    M.x = pyo.Var(M.I, domain=pyo.Binary)

    # Exclude criteria marked as "below"
    excluded_indices = []
    for category, criteria_list in results['below_criteria'].items():
        for criterion in criteria_list:
            if criterion in results['criteria_ids']:
                idx = results['criteria_ids'].index(criterion) + 1
                excluded_indices.append(idx)
            elif criterion.startswith('C'):
                try:
                    idx = int(criterion[1:])
                    if 1 <= idx <= len(results['criteria_ids']):
                        excluded_indices.append(idx)
                except ValueError:
                    pass

    for idx in excluded_indices:
        M.x[idx].fix(0)

    # Model constraints
    M.N = pyo.Var(domain=pyo.NonNegativeIntegers, bounds=(5, 9))
    M.N_eq = pyo.Constraint(expr=M.N == sum(M.x[i] for i in M.I))

    M.d1_minus = pyo.Var(domain=pyo.NonNegativeReals)
    M.d1_plus = pyo.Var(domain=pyo.NonNegativeReals)
    M.d2_minus = pyo.Var(domain=pyo.NonNegativeReals)
    M.d2_plus = pyo.Var(domain=pyo.NonNegativeReals)
    M.par_low = pyo.Constraint(expr=M.N + M.d1_minus - M.d1_plus == omega)
    M.par_high = pyo.Constraint(expr=M.N + M.d2_minus - M.d2_plus == zeta)

    pairs = [(i, j) for i in I for j in I if i < j]
    M.pairs = pyo.Set(initialize=pairs, dimen=2)
    M.h = pyo.Var(M.I, M.I, domain=pyo.Binary)
    M.h1 = pyo.Constraint(M.pairs, rule=lambda M,i,j: M.h[i,j] >= M.x[i] + M.x[j] - 1)
    M.h2 = pyo.Constraint(M.pairs, rule=lambda M,i,j: M.h[i,j] <= M.x[i])
    M.h3 = pyo.Constraint(M.pairs, rule=lambda M,i,j: M.h[i,j] <= M.x[j])

    norm_benefit = {i: (w1*c[i]/tot_c) + (w3*m[i]/tot_m) +
                       (w8*a[i]/tot_a) + (w9*cc[i]/tot_cc)
                    for i in I}

    sens_term = (w6 / tot_s) * sum(s[i]*M.x[i] for i in M.I)
    ce_comp = {i: (tot_ce - ce[i]) / tot_ce for i in I}
    ce_term = w7 * sum(ce_comp[i]*M.x[i] for i in M.I)
    rho = (1/nI) * sum(o[i]*M.x[i] for i in M.I)
    dist_pen = w4 * (sum(r[i,j]*M.h[i,j] for (i,j) in M.pairs) / (nI*(nI-1)/2))
    par_pen = (w5_minus*M.d1_minus + w5_plus*M.d2_plus) / nI

    M.obj = pyo.Objective(
        expr = sum(norm_benefit[i]*M.x[i] for i in M.I)
             + w2*rho + sens_term + ce_term
             - dist_pen - par_pen,
        sense=pyo.maximize
    )

    # Solve
    solver = None
    for name in ("cbc", "highs", "glpk"):
        s = SolverFactory(name)
        if s.available(False):
            solver = s
            break

    if solver is None:
        return None, "No MILP solver found"

    result = solver.solve(M, tee=False)

    if result.solver.termination_condition == TerminationCondition.optimal:
        binary = [int(round(pyo.value(M.x[i]))) for i in I]
        selected = [results['criteria_ids'][i-1] for i in I if int(round(pyo.value(M.x[i]))) == 1]
        not_selected = [results['criteria_ids'][i-1] for i in I if int(round(pyo.value(M.x[i]))) == 0]
        obj_value = pyo.value(M.obj)
        n_value = pyo.value(M.N)
        rho_value = pyo.value((1/len(I))*sum(o[i]*M.x[i] for i in M.I))

        return {
            'status': 'optimal',
            'selected': selected,
            'not_selected': not_selected,
            'binary': binary,
            'n_value': n_value,
            'rho_value': rho_value,
            'obj_value': obj_value,
            'excluded': [results['criteria_ids'][idx-1] for idx in excluded_indices]
        }, None
    else:
        return None, "No optimal solution found"

# ================================================================
# STREAMLIT UI
# ================================================================

def main():
    # Header
    st.title("🎯 Criteria Selection Dashboard")
    st.markdown("*Multi-Criteria Decision Making - Web Application*")
    st.markdown("---")

    # Initialize session state
    if 'results' not in st.session_state:
        st.session_state.results = None
    if 'opt_result' not in st.session_state:
        st.session_state.opt_result = None

    # Sidebar for navigation
    st.sidebar.title("Navigation")
    page = st.sidebar.radio("Go to", ["📝 Template Generator", "📊 Excel Processor", "⚙️ Optimization", "📈 Results"])

    # ============================================================
    # PAGE 1: TEMPLATE GENERATOR
    # ============================================================
    if page == "📝 Template Generator":
        st.header("📝 Template Generator")
        st.markdown("Configure your MCDM parameters and generate an Excel template")

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Configuration")
            alternatives = st.number_input("Number of Alternatives", min_value=3, max_value=20, value=7)
            experts = st.number_input("Number of Experts", min_value=1, max_value=10, value=3)
            criteria = st.number_input("Initial Criteria Count", min_value=5, max_value=30, value=16)
            omega = st.number_input("Target Minimum (ω)", min_value=3, max_value=10, value=5)
            zeta = st.number_input("Target Maximum (ζ)", min_value=5, max_value=15, value=9)

        with col2:
            st.subheader("Thresholds")
            th_completeness = st.number_input("Completeness (α)", value=6.0)
            th_meas_obj = st.number_input("Measurability - Objective (γO)", value=6.5)
            th_meas_subj = st.number_input("Measurability - Subjective (γS)", value=5.5)
            th_correlation = st.number_input("Distinctiveness (δ)", value=0.75)
            th_sensitivity = st.number_input("Sensitivity (θ)", value=0.05)
            th_cost_obj = st.number_input("Cost-effectiveness - Objective (τO)", value=9000.0)
            th_cost_subj = st.number_input("Cost-effectiveness - Subjective (τS)", value=3000.0)
            th_alignment = st.number_input("Alignment (λ)", value=6.5)
            th_cognitive = st.number_input("Cognitive Coherence (μ)", value=7.0)

        if st.button("🔨 Generate Template", use_container_width=True):
            with st.spinner("Generating template..."):
                config = {
                    'alternatives': alternatives,
                    'experts': experts,
                    'criteria': criteria,
                    'omega': omega,
                    'zeta': zeta
                }

                thresholds = {
                    'completeness': th_completeness,
                    'measurability_obj': th_meas_obj,
                    'measurability_subj': th_meas_subj,
                    'correlation': th_correlation,
                    'sensitivity': th_sensitivity,
                    'cost_obj': th_cost_obj,
                    'cost_subj': th_cost_subj,
                    'alignment': th_alignment,
                    'cognitive': th_cognitive
                }

                try:
                    wb = create_excel_template(config, thresholds)

                    # Save to bytes
                    buffer = io.BytesIO()
                    wb.save(buffer)
                    buffer.seek(0)

                    filename = f"MCDM_Template_{criteria}x{alternatives}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"

                    st.success("✅ Template generated successfully!")
                    st.download_button(
                        label="📥 Download Template",
                        data=buffer,
                        file_name=filename,
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        use_container_width=True
                    )
                except Exception as e:
                    st.error(f"Error generating template: {str(e)}")

    # ============================================================
    # PAGE 2: EXCEL PROCESSOR
    # ============================================================
    elif page == "📊 Excel Processor":
        st.header("📊 Excel Processor")
        st.markdown("Upload your completed Excel template for processing")

        uploaded_file = st.file_uploader("Choose an Excel file", type=['xlsx'])

        if uploaded_file is not None:
            if st.button("🔄 Process Excel File", use_container_width=True):
                with st.spinner("Processing Excel file..."):
                    try:
                        processor = MCDMExcelProcessor(uploaded_file)
                        results = processor.process_all_sheets()
                        st.session_state.results = results

                        st.success("✅ Excel file processed successfully!")

                        # Display results
                        col1, col2, col3 = st.columns(3)
                        with col1:
                            st.metric("Criteria", results['num_criteria'])
                        with col2:
                            st.metric("Alternatives", results['num_alternatives'])
                        with col3:
                            st.metric("Experts", results['num_experts'])

                        st.subheader("Data Arrays Extracted")
                        arrays = [
                            ('Completeness', results['c_values']),
                            ('Objectivity', results['o_values']),
                            ('Measurability', results['m_values']),
                            ('Sensitivity', results['s_values']),
                            ('Cost-effectiveness', results['ce_values']),
                            ('Alignment', results['a_values']),
                            ('Cognitive Coherence', results['cc_values']),
                        ]

                        for name, arr in arrays:
                            if arr is not None:
                                st.write(f"✓ **{name}**: {len(arr)} values")
                            else:
                                st.write(f"✗ **{name}**: Not found (will use defaults)")

                        if results['below_criteria']:
                            st.subheader("Criteria Below Thresholds")
                            for category, criteria in results['below_criteria'].items():
                                if criteria:
                                    st.write(f"• **{category}**: {', '.join(criteria)}")

                    except Exception as e:
                        st.error(f"Error processing file: {str(e)}")

        if st.session_state.results is None:
            st.info("👆 Upload an Excel file to get started")

    # ============================================================
    # PAGE 3: OPTIMIZATION
    # ============================================================
    elif page == "⚙️ Optimization":
        st.header("⚙️ Optimization")

        if st.session_state.results is None:
            st.warning("⚠️ Please process an Excel file first!")
            return

        results = st.session_state.results
        st.info(f"📊 Data loaded: {results['num_criteria']} criteria, {results['num_alternatives']} alternatives, {results['num_experts']} experts")

        st.subheader("⚖️ Weight Configuration")

        # Preset selector
        preset = st.selectbox(
            "Choose a preset:",
            ["Equal", "Quality Focus", "Cost Focus", "Balance"]
        )

        presets = {
            "Equal": [1/9] * 9,
            "Quality Focus": [0.15, 0.05, 0.15, 0.10, 0.10, 0.10, 0.05, 0.15, 0.15],
            "Cost Focus": [0.08, 0.10, 0.08, 0.08, 0.15, 0.08, 0.25, 0.09, 0.09],
            "Balance": [0.12, 0.08, 0.11, 0.09, 0.12, 0.10, 0.11, 0.13, 0.14]
        }

        default_weights = presets[preset]

        col1, col2, col3 = st.columns(3)

        with col1:
            w1 = st.number_input("Completeness (w1)", value=default_weights[0], format="%.3f")
            w2 = st.number_input("Objectivity (w2)", value=default_weights[1], format="%.3f")
            w3 = st.number_input("Measurability (w3)", value=default_weights[2], format="%.3f")

        with col2:
            w4 = st.number_input("Distinctiveness (w4)", value=default_weights[3], format="%.3f")
            w5 = st.number_input("Parsimony (w5)", value=default_weights[4], format="%.3f")
            w6 = st.number_input("Sensitivity (w6)", value=default_weights[5], format="%.3f")

        with col3:
            w7 = st.number_input("Cost-effectiveness (w7)", value=default_weights[6], format="%.3f")
            w8 = st.number_input("Alignment (w8)", value=default_weights[7], format="%.3f")
            w9 = st.number_input("Cognitive Coherence (w9)", value=default_weights[8], format="%.3f")

        total = w1 + w2 + w3 + w4 + w5 + w6 + w7 + w8 + w9

        if abs(total - 1.0) < 0.001:
            st.success(f"✅ Sum: {total:.3f}")
        else:
            st.error(f"❌ Sum: {total:.3f} (must equal 1.0)")

        if st.button("🚀 Run Optimization", use_container_width=True):
            if abs(total - 1.0) >= 0.001:
                st.error("⚠️ Weights must sum to 1.0")
                return

            with st.spinner("Running optimization..."):
                try:
                    weights = {
                        'w1': w1, 'w2': w2, 'w3': w3,
                        'w4': w4, 'w5': w5, 'w6': w6,
                        'w7': w7, 'w8': w8, 'w9': w9
                    }

                    opt_result, error = build_optimization_model_with_weights(results, weights)

                    if error:
                        st.error(f"Optimization failed: {error}")
                        return

                    st.session_state.opt_result = opt_result

                    st.success("✅ Optimization completed successfully!")

                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.metric("Status", opt_result['status'].upper())
                    with col2:
                        st.metric("Selected Criteria", int(opt_result['n_value']))
                    with col3:
                        st.metric("Objective Value", f"{opt_result['obj_value']:.4f}")

                    st.subheader("✅ Selected Criteria")
                    for i, crit in enumerate(opt_result['selected'], 1):
                        idx = results['criteria_ids'].index(crit)
                        if idx < len(results['criteria_names']):
                            name = results['criteria_names'][idx]
                            st.write(f"{i}. **{crit}**: {name}")

                    st.subheader("❌ Not Selected")
                    for crit in opt_result['not_selected']:
                        idx = results['criteria_ids'].index(crit)
                        reason = "Below threshold" if crit in opt_result['excluded'] else "Not optimal"
                        if idx < len(results['criteria_names']):
                            name = results['criteria_names'][idx]
                            st.write(f"• **{crit}**: {name} ({reason})")

                except Exception as e:
                    st.error(f"Error: {str(e)}")

    # ============================================================
    # PAGE 4: RESULTS
    # ============================================================
    elif page == "📈 Results":
        st.header("📈 Results Summary")

        if st.session_state.results is None or st.session_state.opt_result is None:
            st.warning("⚠️ Please process data and run optimization first!")
            return

        results = st.session_state.results
        opt_result = st.session_state.opt_result

        # Generate report
        report = f"""============================================================
CRITERIA SELECTION DASHBOARD - COMPLETE RESULTS SUMMARY
============================================================

📊 DATA SUMMARY
----------------------------------------
Total Criteria Evaluated: {results['num_criteria']}
Total Alternatives: {results['num_alternatives']}
Number of Experts: {results['num_experts']}

🎯 OPTIMIZATION RESULTS
----------------------------------------
Optimization Status: {opt_result['status'].upper()}
Objective Function Value: {opt_result['obj_value']:.6f}
Selected Criteria Count: {int(opt_result['n_value'])}
Objectivity Ratio: {opt_result['rho_value']:.4f}

✅ SELECTED CRITERIA
----------------------------------------
"""

        for i, crit in enumerate(opt_result['selected'], 1):
            idx = results['criteria_ids'].index(crit)
            if idx < len(results['criteria_names']):
                name = results['criteria_names'][idx]
                report += f"{i}. {crit}: {name}\n"

        report += "\n❌ EXCLUDED/NOT SELECTED CRITERIA\n"
        report += "-" * 40 + "\n"

        for crit in opt_result['not_selected']:
            idx = results['criteria_ids'].index(crit)
            reason = "Below threshold" if crit in opt_result['excluded'] else "Not optimal"
            if idx < len(results['criteria_names']):
                name = results['criteria_names'][idx]
                report += f"• {crit}: {name} ({reason})\n"

        # Display metrics
        selected_indices = [i-1 for i, val in enumerate(opt_result['binary']) if val == 1]

        if selected_indices:
            st.subheader("📈 Performance Metrics")
            col1, col2, col3, col4 = st.columns(4)

            if results['c_values'] is not None:
                avg_completeness = np.mean([results['c_values'][i] for i in selected_indices])
                col1.metric("Avg Completeness", f"{avg_completeness:.2f}/10")

            if results['m_values'] is not None:
                avg_measurability = np.mean([results['m_values'][i] for i in selected_indices])
                col2.metric("Avg Measurability", f"{avg_measurability:.2f}/10")

            if results['a_values'] is not None:
                avg_alignment = np.mean([results['a_values'][i] for i in selected_indices])
                col3.metric("Avg Alignment", f"{avg_alignment:.2f}/10")

            if results['cc_values'] is not None:
                avg_cognitive = np.mean([results['cc_values'][i] for i in selected_indices])
                col4.metric("Avg Cognitive", f"{avg_cognitive:.2f}/10")

        # Display report
        st.text_area("Full Report", report, height=400)

        # Download button
        st.download_button(
            label="📄 Download Report",
            data=report,
            file_name=f"MCDM_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain",
            use_container_width=True
        )

if __name__ == "__main__":
    main()

