{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3dcf1840-529d-4e14-b635-92b7070ae767",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.11/site-packages (1.45.1)\n",
      "Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (4.2.2)\n",
      "Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging<25,>=20 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (23.1)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (2.1.4)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (10.2.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (5.29.5)\n",
      "Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (14.0.2)\n",
      "Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (2.31.0)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (8.2.2)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (4.14.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (3.1.37)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.11/site-packages (from streamlit) (6.3.3)\n",
      "Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.11/site-packages (from altair<6,>=4.0->streamlit) (3.1.3)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.11/site-packages (from altair<6,>=4.0->streamlit) (4.19.2)\n",
      "Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.11/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas<3,>=1.4.0->streamlit) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas<3,>=1.4.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (2.0.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (2024.6.2)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.11/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.11/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.11/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.11/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.11/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1de68751-9bd3-451a-9748-4a050c73755b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-10-14 13:43:42.112 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.113 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.188 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-10-14 13:43:42.188 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.194 Session state does not function when running a script without `streamlit run`\n",
      "2025-10-14 13:43:42.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-10-14 13:43:42.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "Criteria Selection Dashboard - Streamlit Web Application\n",
    "Converted from Jupyter Notebook\n",
    "\"\"\"\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import openpyxl\n",
    "from openpyxl.styles import Font, PatternFill, Alignment\n",
    "from openpyxl.utils import get_column_letter\n",
    "import os\n",
    "from datetime import datetime\n",
    "import pyomo.environ as pyo\n",
    "from pyomo.opt import SolverFactory, TerminationCondition\n",
    "import re\n",
    "from typing import Dict, List, Tuple, Any\n",
    "import io\n",
    "\n",
    "# ================================================================\n",
    "# PAGE CONFIGURATION\n",
    "# ================================================================\n",
    "st.set_page_config(\n",
    "    page_title=\"Criteria Selection Dashboard\",\n",
    "    page_icon=\"🎯\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# Custom CSS for better styling\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .main {\n",
    "        padding: 2rem;\n",
    "    }\n",
    "    .stButton>button {\n",
    "        width: 100%;\n",
    "    }\n",
    "    .success-box {\n",
    "        padding: 1rem;\n",
    "        background-color: #d4edda;\n",
    "        border-radius: 0.5rem;\n",
    "        border-left: 4px solid #28a745;\n",
    "    }\n",
    "    .info-box {\n",
    "        padding: 1rem;\n",
    "        background-color: #d1ecf1;\n",
    "        border-radius: 0.5rem;\n",
    "        border-left: 4px solid #17a2b8;\n",
    "    }\n",
    "    .warning-box {\n",
    "        padding: 1rem;\n",
    "        background-color: #fff3cd;\n",
    "        border-radius: 0.5rem;\n",
    "        border-left: 4px solid #ffc107;\n",
    "    }\n",
    "    </style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# ================================================================\n",
    "# EXCEL PROCESSOR CLASS (Your existing code - NO CHANGES)\n",
    "# ================================================================\n",
    "class MCDMExcelProcessor:\n",
    "    \"\"\"\n",
    "    A generic processor for MCDM Excel templates that reads and processes\n",
    "    multiple sheets without hardcoding values.\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, excel_file):\n",
    "        \"\"\"Initialize with Excel file (file-like object or path).\"\"\"\n",
    "        self.excel_file = pd.ExcelFile(excel_file)\n",
    "        self.sheet_names = self.excel_file.sheet_names\n",
    "        \n",
    "        # Initialize storage for all arrays and tracking\n",
    "        self.criteria = []\n",
    "        self.criteria_ids = []\n",
    "        self.criteria_names = []\n",
    "        self.alternatives = []\n",
    "        self.experts = []\n",
    "        self.num_criteria = 0\n",
    "        self.num_alternatives = 0\n",
    "        self.num_experts = 0\n",
    "        \n",
    "        # Arrays to be created\n",
    "        self.c_values = None\n",
    "        self.o_values = None\n",
    "        self.m_values = None\n",
    "        self.s_values = None\n",
    "        self.ce_values = None\n",
    "        self.a_values = None\n",
    "        self.cc_values = None\n",
    "        self.r_mat = None\n",
    "        \n",
    "        # Track criteria marked as \"below\"\n",
    "        self.below_criteria = {\n",
    "            'completeness': [],\n",
    "            'measurability': [],\n",
    "            'cognitive_coherence': [],\n",
    "            'alignment': [],\n",
    "            'cost_effectiveness': [],\n",
    "            'sensitivity': []\n",
    "        }\n",
    "        \n",
    "        # Criterion types for normalization\n",
    "        self.criterion_types = {}\n",
    "    \n",
    "    def extract_basic_info(self):\n",
    "        \"\"\"Extract basic information like criteria, alternatives, and experts from the Excel.\"\"\"\n",
    "        # First, try to get criteria from Step1-Completeness\n",
    "        criteria_found = False\n",
    "        for sheet_name in self.sheet_names:\n",
    "            if 'Step1' in sheet_name or 'Completeness' in sheet_name:\n",
    "                df = pd.read_excel(self.excel_file, sheet_name=sheet_name)\n",
    "                \n",
    "                if 'Criterion ID' in df.columns and 'Criterion Name' in df.columns:\n",
    "                    self.criteria_ids = df['Criterion ID'].dropna().tolist()\n",
    "                    self.criteria_names = df['Criterion Name'].dropna().tolist()\n",
    "                    self.criteria = self.criteria_ids if self.criteria_ids else self.criteria_names\n",
    "                    criteria_found = True\n",
    "                    break\n",
    "                elif 'Criterion' in df.columns:\n",
    "                    self.criteria = df['Criterion'].dropna().unique().tolist()\n",
    "                    self.criteria_ids = self.criteria\n",
    "                    self.criteria_names = self.criteria\n",
    "                    criteria_found = True\n",
    "                    break\n",
    "        \n",
    "        # Try to find alternatives from Step6_Sensitivity sheet\n",
    "        alternatives_found = False\n",
    "        for sheet_name in self.sheet_names:\n",
    "            if 'Step6' in sheet_name or 'Sensitivity' in sheet_name:\n",
    "                df = pd.read_excel(self.excel_file, sheet_name=sheet_name, header=None)\n",
    "                \n",
    "                for idx, row in df.iterrows():\n",
    "                    for col_idx, cell in enumerate(row):\n",
    "                        if str(cell).strip() == 'Alternative':\n",
    "                            alt_values = []\n",
    "                            for next_idx in range(idx + 1, min(idx + 10, len(df))):\n",
    "                                alt_value = df.iloc[next_idx, col_idx]\n",
    "                                if pd.notna(alt_value) and str(alt_value).strip():\n",
    "                                    if 'Expert' in str(alt_value) or 'Matrix' in str(alt_value):\n",
    "                                        break\n",
    "                                    alt_values.append(str(alt_value).strip())\n",
    "                            \n",
    "                            if alt_values:\n",
    "                                self.alternatives = alt_values\n",
    "                                alternatives_found = True\n",
    "                                break\n",
    "                    if alternatives_found:\n",
    "                        break\n",
    "                if alternatives_found:\n",
    "                    break\n",
    "        \n",
    "        # Count experts\n",
    "        expert_count = 0\n",
    "        for sheet_name in self.sheet_names:\n",
    "            if 'Step6' in sheet_name or 'Sensitivity' in sheet_name:\n",
    "                df = pd.read_excel(self.excel_file, sheet_name=sheet_name, header=None)\n",
    "                for idx, row in df.iterrows():\n",
    "                    row_str = ' '.join(str(cell) for cell in row if pd.notna(cell))\n",
    "                    if 'Expert' in row_str and ('Decision Matrix' in row_str or 'Matrix' in row_str):\n",
    "                        expert_count += 1\n",
    "                break\n",
    "        \n",
    "        self.num_experts = expert_count if expert_count > 0 else 3\n",
    "        self.num_criteria = len(self.criteria)\n",
    "        self.num_alternatives = len(self.alternatives)\n",
    "        \n",
    "        self.identify_criterion_types()\n",
    "    \n",
    "    def identify_criterion_types(self):\n",
    "        \"\"\"Identify whether criteria are benefits or costs.\"\"\"\n",
    "        cost_keywords = ['cost', 'emission', 'impact', 'time', 'requirement', 'risk', 'complexity']\n",
    "        \n",
    "        if self.criteria_names and len(self.criteria_names) == len(self.criteria_ids):\n",
    "            for crit_id, crit_name in zip(self.criteria_ids, self.criteria_names):\n",
    "                name_lower = crit_name.lower()\n",
    "                is_cost = any(keyword in name_lower for keyword in cost_keywords)\n",
    "                self.criterion_types[crit_id] = 'cost' if is_cost else 'benefit'\n",
    "        else:\n",
    "            for criterion in self.criteria:\n",
    "                criterion_lower = criterion.lower()\n",
    "                is_cost = any(keyword in criterion_lower for keyword in cost_keywords)\n",
    "                self.criterion_types[criterion] = 'cost' if is_cost else 'benefit'\n",
    "    \n",
    "    def find_sheet_by_keyword(self, *keywords):\n",
    "        \"\"\"Find sheet name containing all specified keywords.\"\"\"\n",
    "        for sheet_name in self.sheet_names:\n",
    "            sheet_lower = sheet_name.lower()\n",
    "            if all(keyword.lower() in sheet_lower for keyword in keywords):\n",
    "                return sheet_name\n",
    "        return None\n",
    "    \n",
    "    def process_all_sheets(self):\n",
    "        \"\"\"Process all sheets in sequence.\"\"\"\n",
    "        self.extract_basic_info()\n",
    "        \n",
    "        # Process each step\n",
    "        self.process_step1_completeness()\n",
    "        self.process_step2_objectivity()\n",
    "        self.process_step3_measurability()\n",
    "        self.process_step4_distinctiveness()\n",
    "        self.process_step6_sensitivity()\n",
    "        self.process_step7_cost_effectiveness()\n",
    "        self.process_step8_alignment()\n",
    "        self.process_step9_cognitive_coherence()\n",
    "        \n",
    "        return self.get_results()\n",
    "    \n",
    "    def process_step1_completeness(self):\n",
    "        \"\"\"Process Step1-Completeness sheet.\"\"\"\n",
    "        sheet_name = self.find_sheet_by_keyword('Step1', 'Completeness')\n",
    "        if not sheet_name:\n",
    "            return\n",
    "        \n",
    "        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)\n",
    "        \n",
    "        if 'Average' in df.columns:\n",
    "            self.c_values = df['Average'].dropna().values\n",
    "        elif 'Avg' in df.columns:\n",
    "            self.c_values = df['Avg'].dropna().values\n",
    "        \n",
    "        if 'Status' in df.columns:\n",
    "            status_col = df['Status'].fillna('').astype(str)\n",
    "            below_mask = status_col.str.lower() == 'below'\n",
    "            if 'Criterion ID' in df.columns:\n",
    "                self.below_criteria['completeness'] = df.loc[below_mask, 'Criterion ID'].tolist()\n",
    "    \n",
    "    def process_step2_objectivity(self):\n",
    "        \"\"\"Process Step2_Objectivity sheet.\"\"\"\n",
    "        sheet_name = self.find_sheet_by_keyword('Step2', 'Objectivity')\n",
    "        if not sheet_name:\n",
    "            return\n",
    "        \n",
    "        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)\n",
    "        \n",
    "        if 'Consensus' in df.columns:\n",
    "            self.o_values = df['Consensus'].dropna().values\n",
    "        elif 'Consensus Score' in df.columns:\n",
    "            self.o_values = df['Consensus Score'].dropna().values\n",
    "    \n",
    "    def process_step3_measurability(self):\n",
    "        \"\"\"Process Step3_Measurability sheet.\"\"\"\n",
    "        sheet_name = self.find_sheet_by_keyword('Step3', 'Measurability')\n",
    "        if not sheet_name:\n",
    "            return\n",
    "        \n",
    "        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)\n",
    "        \n",
    "        if 'Average' in df.columns:\n",
    "            self.m_values = df['Average'].dropna().values\n",
    "        elif 'Avg' in df.columns:\n",
    "            self.m_values = df['Avg'].dropna().values\n",
    "        \n",
    "        if 'Status' in df.columns:\n",
    "            status_col = df['Status'].fillna('').astype(str)\n",
    "            below_mask = status_col.str.lower() == 'below'\n",
    "            if 'Criterion ID' in df.columns:\n",
    "                self.below_criteria['measurability'] = df.loc[below_mask, 'Criterion ID'].tolist()\n",
    "    \n",
    "    def process_step4_distinctiveness(self):\n",
    "        \"\"\"Process Step4_Distinctiveness sheet for correlation analysis.\"\"\"\n",
    "        sheet_name = self.find_sheet_by_keyword('Step4', 'Distinctiveness')\n",
    "        if not sheet_name:\n",
    "            return\n",
    "        \n",
    "        decision_matrices = self.read_decision_matrices(sheet_name)\n",
    "        \n",
    "        if decision_matrices:\n",
    "            correlations = []\n",
    "            for expert_name, matrix in decision_matrices.items():\n",
    "                corr_matrix = matrix.corr()\n",
    "                correlations.append(corr_matrix)\n",
    "            \n",
    "            if correlations:\n",
    "                avg_correlation = sum(correlations) / len(correlations)\n",
    "                self.r_mat = avg_correlation.abs().values\n",
    "    \n",
    "    def process_step6_sensitivity(self):\n",
    "        \"\"\"Process Step6_Sensitivity sheet using Monte Carlo simulation.\"\"\"\n",
    "        sheet_name = self.find_sheet_by_keyword('Step6', 'Sensitivity')\n",
    "        if not sheet_name:\n",
    "            return\n",
    "        \n",
    "        decision_matrices = self.read_decision_matrices(sheet_name)\n",
    "        \n",
    "        if not decision_matrices:\n",
    "            return\n",
    "        \n",
    "        normalized_matrices = {}\n",
    "        for expert_name, matrix in decision_matrices.items():\n",
    "            normalized_matrices[expert_name] = self.normalize_matrix(matrix)\n",
    "        \n",
    "        num_simulations = 1000\n",
    "        num_criteria = len(self.criteria)\n",
    "        random_weights = np.random.dirichlet(np.ones(num_criteria), num_simulations)\n",
    "        \n",
    "        sensitivity_results = {}\n",
    "        for expert_name, norm_mat in normalized_matrices.items():\n",
    "            elasticities = pd.DataFrame(index=norm_mat.columns,\n",
    "                                       columns=range(num_simulations))\n",
    "            \n",
    "            for i, weights in enumerate(random_weights):\n",
    "                scores = np.dot(norm_mat.values, weights)\n",
    "                for j, criterion in enumerate(norm_mat.columns):\n",
    "                    w = weights[j]\n",
    "                    elasticity = (norm_mat[criterion] * w).sum() / scores.sum()\n",
    "                    elasticities.loc[criterion, i] = elasticity\n",
    "            \n",
    "            sensitivity_results[expert_name] = elasticities.mean(axis=1)\n",
    "        \n",
    "        if sensitivity_results:\n",
    "            average_elasticity = pd.DataFrame(sensitivity_results).mean(axis=1)\n",
    "            self.s_values = average_elasticity.values\n",
    "            \n",
    "            threshold = 0.05\n",
    "            for i, value in enumerate(self.s_values):\n",
    "                if value < threshold:\n",
    "                    if i < len(self.criteria):\n",
    "                        criterion = self.criteria[i]\n",
    "                        if criterion not in self.below_criteria['sensitivity']:\n",
    "                            self.below_criteria['sensitivity'].append(criterion)\n",
    "    \n",
    "    def process_step7_cost_effectiveness(self):\n",
    "        \"\"\"Process Step7_Cost_effectiveness sheet.\"\"\"\n",
    "        sheet_name = self.find_sheet_by_keyword('Step7', 'Cost')\n",
    "        if not sheet_name:\n",
    "            return\n",
    "        \n",
    "        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)\n",
    "        \n",
    "        costs = np.zeros(self.num_criteria)\n",
    "        expert_ratings = np.zeros((self.num_criteria, self.num_experts))\n",
    "        \n",
    "        crit_col = 'Criterion ID' if 'Criterion ID' in df.columns else 'Criterion'\n",
    "        cost_col = None\n",
    "        for col in df.columns:\n",
    "            if 'Cost' in str(col) or 'Evaluation Cost' in str(col):\n",
    "                cost_col = col\n",
    "                break\n",
    "        \n",
    "        expert_cols = [col for col in df.columns if 'Expert' in str(col) or 'Rating' in str(col)]\n",
    "        \n",
    "        if crit_col and cost_col:\n",
    "            crit_to_idx = {crit: i for i, crit in enumerate(self.criteria)}\n",
    "            \n",
    "            for _, row in df.iterrows():\n",
    "                if pd.notna(row[crit_col]):\n",
    "                    criterion = str(row[crit_col])\n",
    "                    if criterion in crit_to_idx:\n",
    "                        idx = crit_to_idx[criterion]\n",
    "                        \n",
    "                        if pd.notna(row[cost_col]):\n",
    "                            costs[idx] = float(row[cost_col])\n",
    "                        \n",
    "                        for j, expert_col in enumerate(expert_cols[:self.num_experts]):\n",
    "                            if pd.notna(row[expert_col]):\n",
    "                                expert_ratings[idx, j] = float(row[expert_col])\n",
    "        \n",
    "        if np.any(costs > 0) and np.any(expert_ratings > 0):\n",
    "            average_scores = np.mean(expert_ratings, axis=1)\n",
    "            effectiveness_weights = np.ones(self.num_criteria)\n",
    "            for i in range(self.num_criteria):\n",
    "                if average_scores[i] > 0:\n",
    "                    effectiveness_weights[i] = 1 - (average_scores[i] - 5) / 5\n",
    "                    effectiveness_weights[i] = max(0.1, min(2.0, effectiveness_weights[i]))\n",
    "            \n",
    "            self.ce_values = costs * effectiveness_weights\n",
    "        \n",
    "        if 'Status' in df.columns:\n",
    "            status_col = df['Status'].fillna('').astype(str)\n",
    "            below_mask = status_col.str.lower() == 'below'\n",
    "            if crit_col:\n",
    "                self.below_criteria['cost_effectiveness'] = df.loc[below_mask, crit_col].tolist()\n",
    "    \n",
    "    def process_step8_alignment(self):\n",
    "        \"\"\"Process Step8_Alignment sheet.\"\"\"\n",
    "        sheet_name = self.find_sheet_by_keyword('Step8', 'Alignment')\n",
    "        if not sheet_name:\n",
    "            return\n",
    "        \n",
    "        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)\n",
    "        \n",
    "        if 'Average' in df.columns:\n",
    "            self.a_values = df['Average'].dropna().values\n",
    "        elif 'Avg' in df.columns:\n",
    "            self.a_values = df['Avg'].dropna().values\n",
    "        \n",
    "        if 'Status' in df.columns:\n",
    "            status_col = df['Status'].fillna('').astype(str)\n",
    "            below_mask = status_col.str.lower() == 'below'\n",
    "            if 'Criterion ID' in df.columns:\n",
    "                self.below_criteria['alignment'] = df.loc[below_mask, 'Criterion ID'].tolist()\n",
    "    \n",
    "    def process_step9_cognitive_coherence(self):\n",
    "        \"\"\"Process Step9_Cognitive_Coherence sheet.\"\"\"\n",
    "        sheet_name = self.find_sheet_by_keyword('Step9', 'Cognitive', 'Coherence')\n",
    "        if not sheet_name:\n",
    "            return\n",
    "        \n",
    "        df = pd.read_excel(self.excel_file, sheet_name=sheet_name)\n",
    "        \n",
    "        if 'Average' in df.columns:\n",
    "            self.cc_values = df['Average'].dropna().values\n",
    "        elif 'Avg' in df.columns:\n",
    "            self.cc_values = df['Avg'].dropna().values\n",
    "        \n",
    "        if 'Status' in df.columns:\n",
    "            status_col = df['Status'].fillna('').astype(str)\n",
    "            below_mask = status_col.str.lower() == 'below'\n",
    "            if 'Criterion ID' in df.columns:\n",
    "                self.below_criteria['cognitive_coherence'] = df.loc[below_mask, 'Criterion ID'].tolist()\n",
    "    \n",
    "    def read_decision_matrices(self, sheet_name):\n",
    "        \"\"\"Read decision matrices from a sheet.\"\"\"\n",
    "        df_full = pd.read_excel(self.excel_file, sheet_name=sheet_name, header=None)\n",
    "        decision_matrices = {}\n",
    "        \n",
    "        expert_markers = []\n",
    "        for idx, row in df_full.iterrows():\n",
    "            row_str = ' '.join(str(cell) for cell in row if pd.notna(cell))\n",
    "            if 'Expert' in row_str and ('Decision Matrix' in row_str or 'Matrix' in row_str):\n",
    "                match = re.search(r'Expert\\s*(\\d+)', row_str)\n",
    "                if match:\n",
    "                    expert_num = int(match.group(1))\n",
    "                    expert_markers.append((idx, f'Expert {expert_num}'))\n",
    "        \n",
    "        if expert_markers:\n",
    "            for i, (start_row, expert_name) in enumerate(expert_markers):\n",
    "                if i < len(expert_markers) - 1:\n",
    "                    end_row = expert_markers[i + 1][0] - 1\n",
    "                else:\n",
    "                    end_row = start_row + 20\n",
    "                \n",
    "                try:\n",
    "                    df_matrix = pd.read_excel(self.excel_file, sheet_name=sheet_name,\n",
    "                                            skiprows=start_row + 1,\n",
    "                                            nrows=min(end_row - start_row - 1, 10))\n",
    "                    \n",
    "                    if not df_matrix.empty:\n",
    "                        alt_col = None\n",
    "                        for col in df_matrix.columns:\n",
    "                            if 'Alternative' in str(col) or 'Option' in str(col):\n",
    "                                alt_col = col\n",
    "                                break\n",
    "                        \n",
    "                        if alt_col is None and not df_matrix.columns[0].startswith('Unnamed'):\n",
    "                            alt_col = df_matrix.columns[0]\n",
    "                        \n",
    "                        if alt_col:\n",
    "                            valid_alts = df_matrix[alt_col].dropna()\n",
    "                            valid_alts = [alt for alt in valid_alts if \n",
    "                                        isinstance(alt, str) and \n",
    "                                        len(alt) > 5 and\n",
    "                                        'Expert' not in alt and\n",
    "                                        'Matrix' not in alt]\n",
    "                            \n",
    "                            if valid_alts:\n",
    "                                criteria_cols = []\n",
    "                                for col in df_matrix.columns:\n",
    "                                    if col != alt_col and not str(col).startswith('Unnamed'):\n",
    "                                        if col in self.criteria or col in self.criteria_ids or col in self.criteria_names:\n",
    "                                            criteria_cols.append(col)\n",
    "                                \n",
    "                                if not criteria_cols:\n",
    "                                    criteria_cols = [col for col in df_matrix.columns \n",
    "                                                   if col != alt_col and \n",
    "                                                   not str(col).startswith('Unnamed')]\n",
    "                                \n",
    "                                if criteria_cols:\n",
    "                                    matrix_data = df_matrix.loc[df_matrix[alt_col].isin(valid_alts), criteria_cols]\n",
    "                                    matrix_data.index = valid_alts[:len(matrix_data)]\n",
    "                                    \n",
    "                                    for col in matrix_data.columns:\n",
    "                                        matrix_data[col] = pd.to_numeric(matrix_data[col], errors='coerce')\n",
    "                                    \n",
    "                                    matrix_data = matrix_data.dropna(how='all').dropna(axis=1, how='all')\n",
    "                                    \n",
    "                                    if not matrix_data.empty:\n",
    "                                        decision_matrices[expert_name] = matrix_data\n",
    "                \n",
    "                except Exception as e:\n",
    "                    continue\n",
    "        \n",
    "        return decision_matrices\n",
    "    \n",
    "    def normalize_matrix(self, matrix):\n",
    "        \"\"\"Normalize matrix with benefit/cost logic.\"\"\"\n",
    "        norm = matrix.copy()\n",
    "        for col in matrix.columns:\n",
    "            max_val = matrix[col].max()\n",
    "            min_val = matrix[col].min()\n",
    "            \n",
    "            if max_val == min_val:\n",
    "                norm[col] = 1.0\n",
    "            elif self.criterion_types.get(col, 'benefit') == 'benefit':\n",
    "                norm[col] = (matrix[col] - min_val) / (max_val - min_val)\n",
    "            else:\n",
    "                norm[col] = (max_val - matrix[col]) / (max_val - min_val)\n",
    "        \n",
    "        return norm\n",
    "    \n",
    "    def get_results(self):\n",
    "        \"\"\"Return all processed results.\"\"\"\n",
    "        results = {\n",
    "            'criteria': self.criteria,\n",
    "            'criteria_ids': self.criteria_ids,\n",
    "            'criteria_names': self.criteria_names,\n",
    "            'alternatives': self.alternatives,\n",
    "            'num_criteria': self.num_criteria,\n",
    "            'num_alternatives': self.num_alternatives,\n",
    "            'num_experts': self.num_experts,\n",
    "            'c_values': self.c_values,\n",
    "            'o_values': self.o_values,\n",
    "            'm_values': self.m_values,\n",
    "            's_values': self.s_values,\n",
    "            'ce_values': self.ce_values,\n",
    "            'a_values': self.a_values,\n",
    "            'cc_values': self.cc_values,\n",
    "            'r_mat': self.r_mat,\n",
    "            'below_criteria': self.below_criteria,\n",
    "            'criterion_types': self.criterion_types\n",
    "        }\n",
    "        \n",
    "        return results\n",
    "\n",
    "# ================================================================\n",
    "# TEMPLATE GENERATOR FUNCTIONS (Your existing code - NO CHANGES)\n",
    "# ================================================================\n",
    "def create_excel_template(config, thresholds):\n",
    "    \"\"\"Create the MCDM Excel template\"\"\"\n",
    "    wb = openpyxl.Workbook()\n",
    "    wb.remove(wb.active)\n",
    "    \n",
    "    alternatives = [f\"Alternative {i+1}\" for i in range(config['alternatives'])]\n",
    "    \n",
    "    # Create all sheets\n",
    "    create_instructions_sheet(wb, config, thresholds)\n",
    "    create_step1_completeness(wb, config, thresholds)\n",
    "    create_step2_objectivity(wb, config)\n",
    "    create_step3_measurability(wb, config, thresholds)\n",
    "    create_step4_distinctiveness(wb, config, alternatives)\n",
    "    create_step5_parsimony(wb, config)\n",
    "    create_step6_sensitivity(wb, config, alternatives)\n",
    "    create_step7_cost_effectiveness(wb, config, thresholds)\n",
    "    create_step8_alignment(wb, config, thresholds)\n",
    "    create_step9_cognitive_coherence(wb, config, thresholds)\n",
    "    \n",
    "    return wb\n",
    "\n",
    "# [Include all your sheet creation functions here - I'll abbreviate for space]\n",
    "def create_instructions_sheet(wb, config, thresholds):\n",
    "    ws = wb.create_sheet(\"Instructions\")\n",
    "    instructions = [\n",
    "        [\"CRITERIA SELECTION DASHBOARD - EXCEL TEMPLATE\"],\n",
    "        [],\n",
    "        [\"CONFIGURATION SUMMARY:\"],\n",
    "        [f\"Alternatives: {config['alternatives']}\", f\"Experts: {config['experts']}\", f\"Criteria: {config['criteria']}\"],\n",
    "        [f\"Target Range: ω={config['omega']}, ζ={config['zeta']}\"],\n",
    "        [],\n",
    "        [\"Fill in the YELLOW highlighted cells with your data\"],\n",
    "    ]\n",
    "    for row_idx, row_data in enumerate(instructions, 1):\n",
    "        for col_idx, value in enumerate(row_data, 1):\n",
    "            ws.cell(row=row_idx, column=col_idx, value=value)\n",
    "\n",
    "def create_step1_completeness(wb, config, thresholds):\n",
    "    ws = wb.create_sheet(\"Step1_Completeness\")\n",
    "    ws['A1'] = \"Step 1: Completeness Evaluation\"\n",
    "    ws['A2'] = \"Rate how well each criterion covers the decision aspect (1-10 scale)\"\n",
    "    \n",
    "    row = 5\n",
    "    headers = [\"Criterion ID\", \"Criterion Name\"]\n",
    "    for e in range(config['experts']):\n",
    "        headers.append(f\"Expert_{e+1}\")\n",
    "    headers.extend([\"Average\", \"Status\"])\n",
    "    \n",
    "    for col_idx, header in enumerate(headers, 1):\n",
    "        cell = ws.cell(row=row, column=col_idx, value=header)\n",
    "        cell.font = Font(bold=True)\n",
    "    \n",
    "    for i in range(config['criteria']):\n",
    "        row_num = 6 + i\n",
    "        ws.cell(row=row_num, column=1, value=f\"C{i+1}\")\n",
    "        ws.cell(row=row_num, column=2, value=f\"Criterion {i+1}\")\n",
    "        \n",
    "        for e in range(config['experts']):\n",
    "            cell = ws.cell(row=row_num, column=3+e)\n",
    "            cell.fill = PatternFill(start_color=\"FFF2CC\", end_color=\"FFF2CC\", fill_type=\"solid\")\n",
    "        \n",
    "        first_expert_col = get_column_letter(3)\n",
    "        last_expert_col = get_column_letter(2 + config['experts'])\n",
    "        avg_col = get_column_letter(3 + config['experts'])\n",
    "        \n",
    "        avg_cell = ws.cell(row=row_num, column=3 + config['experts'])\n",
    "        avg_cell.value = f'=IFERROR(AVERAGE({first_expert_col}{row_num}:{last_expert_col}{row_num}),\"\")'\n",
    "        \n",
    "        status_cell = ws.cell(row=row_num, column=4 + config['experts'])\n",
    "        status_cell.value = f'=IF({avg_col}{row_num}=\"\",\"\",IF({avg_col}{row_num}>={thresholds[\"completeness\"]},\"Meets\",\"Below\"))'\n",
    "\n",
    "def create_step2_objectivity(wb, config):\n",
    "    ws = wb.create_sheet(\"Step2_Objectivity\")\n",
    "    ws['A1'] = \"Step 2: Objectivity Classification\"\n",
    "    # Similar implementation...\n",
    "    pass\n",
    "\n",
    "def create_step3_measurability(wb, config, thresholds):\n",
    "    ws = wb.create_sheet(\"Step3_Measurability\")\n",
    "    ws['A1'] = \"Step 3: Measurability Assessment\"\n",
    "    # Similar implementation...\n",
    "    pass\n",
    "\n",
    "def create_step4_distinctiveness(wb, config, alternatives):\n",
    "    ws = wb.create_sheet(\"Step4_Distinctiveness\")\n",
    "    ws['A1'] = \"Step 4: Distinctiveness Analysis\"\n",
    "    # Similar implementation...\n",
    "    pass\n",
    "\n",
    "def create_step5_parsimony(wb, config):\n",
    "    ws = wb.create_sheet(\"Step5_Parsimony\")\n",
    "    ws['A1'] = \"Step 5: Parsimony Configuration\"\n",
    "    # Similar implementation...\n",
    "    pass\n",
    "\n",
    "def create_step6_sensitivity(wb, config, alternatives):\n",
    "    ws = wb.create_sheet(\"Step6_Sensitivity\")\n",
    "    ws['A1'] = \"Step 6: Sensitivity Analysis\"\n",
    "    # Similar implementation...\n",
    "    pass\n",
    "\n",
    "def create_step7_cost_effectiveness(wb, config, thresholds):\n",
    "    ws = wb.create_sheet(\"Step7_Cost_Effectiveness\")\n",
    "    ws['A1'] = \"Step 7: Cost-Effectiveness Evaluation\"\n",
    "    # Similar implementation...\n",
    "    pass\n",
    "\n",
    "def create_step8_alignment(wb, config, thresholds):\n",
    "    ws = wb.create_sheet(\"Step8_Alignment\")\n",
    "    ws['A1'] = \"Step 8: Alignment Assessment\"\n",
    "    # Similar implementation...\n",
    "    pass\n",
    "\n",
    "def create_step9_cognitive_coherence(wb, config, thresholds):\n",
    "    ws = wb.create_sheet(\"Step9_Cognitive_Coherence\")\n",
    "    ws['A1'] = \"Step 9: Cognitive Coherence Evaluation\"\n",
    "    # Similar implementation...\n",
    "    pass\n",
    "\n",
    "# ================================================================\n",
    "# OPTIMIZATION MODEL (Your existing code - NO CHANGES)\n",
    "# ================================================================\n",
    "def build_optimization_model_with_weights(results, weights):\n",
    "    \"\"\"Build and solve the optimization model with custom weights\"\"\"\n",
    "    I = list(range(1, results['num_criteria'] + 1))\n",
    "    \n",
    "    # Extract weights\n",
    "    w1 = weights['w1']\n",
    "    w2 = weights['w2']\n",
    "    w3 = weights['w3']\n",
    "    w4 = weights['w4']\n",
    "    w5 = weights['w5']\n",
    "    w6 = weights['w6']\n",
    "    w7 = weights['w7']\n",
    "    w8 = weights['w8']\n",
    "    w9 = weights['w9']\n",
    "    \n",
    "    w5_minus = w5 / 2\n",
    "    w5_plus = w5 / 2\n",
    "    \n",
    "    omega, zeta = 5, 9\n",
    "    nI = len(I)\n",
    "    \n",
    "    # Data dictionaries\n",
    "    c = {i: results['c_values'][i-1] if results['c_values'] is not None else 5.0 for i in I}\n",
    "    m = {i: results['m_values'][i-1] if results['m_values'] is not None else 5.0 for i in I}\n",
    "    s = {i: results['s_values'][i-1] if results['s_values'] is not None else 0.1 for i in I}\n",
    "    ce = {i: results['ce_values'][i-1] if results['ce_values'] is not None else 1000.0 for i in I}\n",
    "    a = {i: results['a_values'][i-1] if results['a_values'] is not None else 5.0 for i in I}\n",
    "    cc = {i: results['cc_values'][i-1] if results['cc_values'] is not None else 5.0 for i in I}\n",
    "    o = {i: results['o_values'][i-1] if results['o_values'] is not None else 0.5 for i in I}\n",
    "    \n",
    "    if results['r_mat'] is not None:\n",
    "        r = {(i, j): results['r_mat'][i-1][j-1] for i in I for j in I if i < j}\n",
    "    else:\n",
    "        r = {(i, j): 0.0 for i in I for j in I if i < j}\n",
    "    \n",
    "    tot_c = sum(c.values())\n",
    "    tot_m = sum(m.values())\n",
    "    tot_a = sum(a.values())\n",
    "    tot_cc = sum(cc.values())\n",
    "    tot_s = sum(s.values())\n",
    "    tot_ce = sum(ce.values())\n",
    "    \n",
    "    # Build model\n",
    "    M = pyo.ConcreteModel()\n",
    "    M.I = pyo.Set(initialize=I)\n",
    "    M.x = pyo.Var(M.I, domain=pyo.Binary)\n",
    "    \n",
    "    # Exclude criteria marked as \"below\"\n",
    "    excluded_indices = []\n",
    "    for category, criteria_list in results['below_criteria'].items():\n",
    "        for criterion in criteria_list:\n",
    "            if criterion in results['criteria_ids']:\n",
    "                idx = results['criteria_ids'].index(criterion) + 1\n",
    "                excluded_indices.append(idx)\n",
    "            elif criterion.startswith('C'):\n",
    "                try:\n",
    "                    idx = int(criterion[1:])\n",
    "                    if 1 <= idx <= len(results['criteria_ids']):\n",
    "                        excluded_indices.append(idx)\n",
    "                except ValueError:\n",
    "                    pass\n",
    "    \n",
    "    for idx in excluded_indices:\n",
    "        M.x[idx].fix(0)\n",
    "    \n",
    "    # Model constraints\n",
    "    M.N = pyo.Var(domain=pyo.NonNegativeIntegers, bounds=(5, 9))\n",
    "    M.N_eq = pyo.Constraint(expr=M.N == sum(M.x[i] for i in M.I))\n",
    "    \n",
    "    M.d1_minus = pyo.Var(domain=pyo.NonNegativeReals)\n",
    "    M.d1_plus = pyo.Var(domain=pyo.NonNegativeReals)\n",
    "    M.d2_minus = pyo.Var(domain=pyo.NonNegativeReals)\n",
    "    M.d2_plus = pyo.Var(domain=pyo.NonNegativeReals)\n",
    "    M.par_low = pyo.Constraint(expr=M.N + M.d1_minus - M.d1_plus == omega)\n",
    "    M.par_high = pyo.Constraint(expr=M.N + M.d2_minus - M.d2_plus == zeta)\n",
    "    \n",
    "    pairs = [(i, j) for i in I for j in I if i < j]\n",
    "    M.pairs = pyo.Set(initialize=pairs, dimen=2)\n",
    "    M.h = pyo.Var(M.I, M.I, domain=pyo.Binary)\n",
    "    M.h1 = pyo.Constraint(M.pairs, rule=lambda M,i,j: M.h[i,j] >= M.x[i] + M.x[j] - 1)\n",
    "    M.h2 = pyo.Constraint(M.pairs, rule=lambda M,i,j: M.h[i,j] <= M.x[i])\n",
    "    M.h3 = pyo.Constraint(M.pairs, rule=lambda M,i,j: M.h[i,j] <= M.x[j])\n",
    "    \n",
    "    norm_benefit = {i: (w1*c[i]/tot_c) + (w3*m[i]/tot_m) +\n",
    "                       (w8*a[i]/tot_a) + (w9*cc[i]/tot_cc)\n",
    "                    for i in I}\n",
    "    \n",
    "    sens_term = (w6 / tot_s) * sum(s[i]*M.x[i] for i in M.I)\n",
    "    ce_comp = {i: (tot_ce - ce[i]) / tot_ce for i in I}\n",
    "    ce_term = w7 * sum(ce_comp[i]*M.x[i] for i in M.I)\n",
    "    rho = (1/nI) * sum(o[i]*M.x[i] for i in M.I)\n",
    "    dist_pen = w4 * (sum(r[i,j]*M.h[i,j] for (i,j) in M.pairs) / (nI*(nI-1)/2))\n",
    "    par_pen = (w5_minus*M.d1_minus + w5_plus*M.d2_plus) / nI\n",
    "    \n",
    "    M.obj = pyo.Objective(\n",
    "        expr = sum(norm_benefit[i]*M.x[i] for i in M.I)\n",
    "             + w2*rho + sens_term + ce_term\n",
    "             - dist_pen - par_pen,\n",
    "        sense=pyo.maximize\n",
    "    )\n",
    "    \n",
    "    # Solve\n",
    "    solver = None\n",
    "    for name in (\"cbc\", \"highs\", \"glpk\"):\n",
    "        s = SolverFactory(name)\n",
    "        if s.available(False):\n",
    "            solver = s\n",
    "            break\n",
    "    \n",
    "    if solver is None:\n",
    "        return None, \"No MILP solver found\"\n",
    "    \n",
    "    result = solver.solve(M, tee=False)\n",
    "    \n",
    "    if result.solver.termination_condition == TerminationCondition.optimal:\n",
    "        binary = [int(round(pyo.value(M.x[i]))) for i in I]\n",
    "        selected = [results['criteria_ids'][i-1] for i in I if int(round(pyo.value(M.x[i]))) == 1]\n",
    "        not_selected = [results['criteria_ids'][i-1] for i in I if int(round(pyo.value(M.x[i]))) == 0]\n",
    "        obj_value = pyo.value(M.obj)\n",
    "        n_value = pyo.value(M.N)\n",
    "        rho_value = pyo.value((1/len(I))*sum(o[i]*M.x[i] for i in M.I))\n",
    "        \n",
    "        return {\n",
    "            'status': 'optimal',\n",
    "            'selected': selected,\n",
    "            'not_selected': not_selected,\n",
    "            'binary': binary,\n",
    "            'n_value': n_value,\n",
    "            'rho_value': rho_value,\n",
    "            'obj_value': obj_value,\n",
    "            'excluded': [results['criteria_ids'][idx-1] for idx in excluded_indices]\n",
    "        }, None\n",
    "    else:\n",
    "        return None, \"No optimal solution found\"\n",
    "\n",
    "# ================================================================\n",
    "# STREAMLIT UI\n",
    "# ================================================================\n",
    "\n",
    "def main():\n",
    "    # Header\n",
    "    st.title(\"🎯 Criteria Selection Dashboard\")\n",
    "    st.markdown(\"*Multi-Criteria Decision Making - Web Application*\")\n",
    "    st.markdown(\"---\")\n",
    "    \n",
    "    # Initialize session state\n",
    "    if 'results' not in st.session_state:\n",
    "        st.session_state.results = None\n",
    "    if 'opt_result' not in st.session_state:\n",
    "        st.session_state.opt_result = None\n",
    "    \n",
    "    # Sidebar for navigation\n",
    "    st.sidebar.title(\"Navigation\")\n",
    "    page = st.sidebar.radio(\"Go to\", [\"📝 Template Generator\", \"📊 Excel Processor\", \"⚙️ Optimization\", \"📈 Results\"])\n",
    "    \n",
    "    # ============================================================\n",
    "    # PAGE 1: TEMPLATE GENERATOR\n",
    "    # ============================================================\n",
    "    if page == \"📝 Template Generator\":\n",
    "        st.header(\"📝 Template Generator\")\n",
    "        st.markdown(\"Configure your MCDM parameters and generate an Excel template\")\n",
    "        \n",
    "        col1, col2 = st.columns(2)\n",
    "        \n",
    "        with col1:\n",
    "            st.subheader(\"Configuration\")\n",
    "            alternatives = st.number_input(\"Number of Alternatives\", min_value=3, max_value=20, value=7)\n",
    "            experts = st.number_input(\"Number of Experts\", min_value=1, max_value=10, value=3)\n",
    "            criteria = st.number_input(\"Initial Criteria Count\", min_value=5, max_value=30, value=16)\n",
    "            omega = st.number_input(\"Target Minimum (ω)\", min_value=3, max_value=10, value=5)\n",
    "            zeta = st.number_input(\"Target Maximum (ζ)\", min_value=5, max_value=15, value=9)\n",
    "        \n",
    "        with col2:\n",
    "            st.subheader(\"Thresholds\")\n",
    "            th_completeness = st.number_input(\"Completeness (α)\", value=6.0)\n",
    "            th_meas_obj = st.number_input(\"Measurability - Objective (γO)\", value=6.5)\n",
    "            th_meas_subj = st.number_input(\"Measurability - Subjective (γS)\", value=5.5)\n",
    "            th_correlation = st.number_input(\"Distinctiveness (δ)\", value=0.75)\n",
    "            th_sensitivity = st.number_input(\"Sensitivity (θ)\", value=0.05)\n",
    "            th_cost_obj = st.number_input(\"Cost-effectiveness - Objective (τO)\", value=9000.0)\n",
    "            th_cost_subj = st.number_input(\"Cost-effectiveness - Subjective (τS)\", value=3000.0)\n",
    "            th_alignment = st.number_input(\"Alignment (λ)\", value=6.5)\n",
    "            th_cognitive = st.number_input(\"Cognitive Coherence (μ)\", value=7.0)\n",
    "        \n",
    "        if st.button(\"🔨 Generate Template\", use_container_width=True):\n",
    "            with st.spinner(\"Generating template...\"):\n",
    "                config = {\n",
    "                    'alternatives': alternatives,\n",
    "                    'experts': experts,\n",
    "                    'criteria': criteria,\n",
    "                    'omega': omega,\n",
    "                    'zeta': zeta\n",
    "                }\n",
    "                \n",
    "                thresholds = {\n",
    "                    'completeness': th_completeness,\n",
    "                    'measurability_obj': th_meas_obj,\n",
    "                    'measurability_subj': th_meas_subj,\n",
    "                    'correlation': th_correlation,\n",
    "                    'sensitivity': th_sensitivity,\n",
    "                    'cost_obj': th_cost_obj,\n",
    "                    'cost_subj': th_cost_subj,\n",
    "                    'alignment': th_alignment,\n",
    "                    'cognitive': th_cognitive\n",
    "                }\n",
    "                \n",
    "                try:\n",
    "                    wb = create_excel_template(config, thresholds)\n",
    "                    \n",
    "                    # Save to bytes\n",
    "                    buffer = io.BytesIO()\n",
    "                    wb.save(buffer)\n",
    "                    buffer.seek(0)\n",
    "                    \n",
    "                    filename = f\"MCDM_Template_{criteria}x{alternatives}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx\"\n",
    "                    \n",
    "                    st.success(\"✅ Template generated successfully!\")\n",
    "                    st.download_button(\n",
    "                        label=\"📥 Download Template\",\n",
    "                        data=buffer,\n",
    "                        file_name=filename,\n",
    "                        mime=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\",\n",
    "                        use_container_width=True\n",
    "                    )\n",
    "                except Exception as e:\n",
    "                    st.error(f\"Error generating template: {str(e)}\")\n",
    "    \n",
    "    # ============================================================\n",
    "    # PAGE 2: EXCEL PROCESSOR\n",
    "    # ============================================================\n",
    "    elif page == \"📊 Excel Processor\":\n",
    "        st.header(\"📊 Excel Processor\")\n",
    "        st.markdown(\"Upload your completed Excel template for processing\")\n",
    "        \n",
    "        uploaded_file = st.file_uploader(\"Choose an Excel file\", type=['xlsx'])\n",
    "        \n",
    "        if uploaded_file is not None:\n",
    "            if st.button(\"🔄 Process Excel File\", use_container_width=True):\n",
    "                with st.spinner(\"Processing Excel file...\"):\n",
    "                    try:\n",
    "                        processor = MCDMExcelProcessor(uploaded_file)\n",
    "                        results = processor.process_all_sheets()\n",
    "                        st.session_state.results = results\n",
    "                        \n",
    "                        st.success(\"✅ Excel file processed successfully!\")\n",
    "                        \n",
    "                        # Display results\n",
    "                        col1, col2, col3 = st.columns(3)\n",
    "                        with col1:\n",
    "                            st.metric(\"Criteria\", results['num_criteria'])\n",
    "                        with col2:\n",
    "                            st.metric(\"Alternatives\", results['num_alternatives'])\n",
    "                        with col3:\n",
    "                            st.metric(\"Experts\", results['num_experts'])\n",
    "                        \n",
    "                        st.subheader(\"Data Arrays Extracted\")\n",
    "                        arrays = [\n",
    "                            ('Completeness', results['c_values']),\n",
    "                            ('Objectivity', results['o_values']),\n",
    "                            ('Measurability', results['m_values']),\n",
    "                            ('Sensitivity', results['s_values']),\n",
    "                            ('Cost-effectiveness', results['ce_values']),\n",
    "                            ('Alignment', results['a_values']),\n",
    "                            ('Cognitive Coherence', results['cc_values']),\n",
    "                        ]\n",
    "                        \n",
    "                        for name, arr in arrays:\n",
    "                            if arr is not None:\n",
    "                                st.write(f\"✓ **{name}**: {len(arr)} values\")\n",
    "                            else:\n",
    "                                st.write(f\"✗ **{name}**: Not found (will use defaults)\")\n",
    "                        \n",
    "                        if results['below_criteria']:\n",
    "                            st.subheader(\"Criteria Below Thresholds\")\n",
    "                            for category, criteria in results['below_criteria'].items():\n",
    "                                if criteria:\n",
    "                                    st.write(f\"• **{category}**: {', '.join(criteria)}\")\n",
    "                    \n",
    "                    except Exception as e:\n",
    "                        st.error(f\"Error processing file: {str(e)}\")\n",
    "        \n",
    "        if st.session_state.results is None:\n",
    "            st.info(\"👆 Upload an Excel file to get started\")\n",
    "    \n",
    "    # ============================================================\n",
    "    # PAGE 3: OPTIMIZATION\n",
    "    # ============================================================\n",
    "    elif page == \"⚙️ Optimization\":\n",
    "        st.header(\"⚙️ Optimization\")\n",
    "        \n",
    "        if st.session_state.results is None:\n",
    "            st.warning(\"⚠️ Please process an Excel file first!\")\n",
    "            return\n",
    "        \n",
    "        results = st.session_state.results\n",
    "        st.info(f\"📊 Data loaded: {results['num_criteria']} criteria, {results['num_alternatives']} alternatives, {results['num_experts']} experts\")\n",
    "        \n",
    "        st.subheader(\"⚖️ Weight Configuration\")\n",
    "        \n",
    "        # Preset selector\n",
    "        preset = st.selectbox(\n",
    "            \"Choose a preset:\",\n",
    "            [\"Equal\", \"Quality Focus\", \"Cost Focus\", \"Balance\"]\n",
    "        )\n",
    "        \n",
    "        presets = {\n",
    "            \"Equal\": [1/9] * 9,\n",
    "            \"Quality Focus\": [0.15, 0.05, 0.15, 0.10, 0.10, 0.10, 0.05, 0.15, 0.15],\n",
    "            \"Cost Focus\": [0.08, 0.10, 0.08, 0.08, 0.15, 0.08, 0.25, 0.09, 0.09],\n",
    "            \"Balance\": [0.12, 0.08, 0.11, 0.09, 0.12, 0.10, 0.11, 0.13, 0.14]\n",
    "        }\n",
    "        \n",
    "        default_weights = presets[preset]\n",
    "        \n",
    "        col1, col2, col3 = st.columns(3)\n",
    "        \n",
    "        with col1:\n",
    "            w1 = st.number_input(\"Completeness (w1)\", value=default_weights[0], format=\"%.3f\")\n",
    "            w2 = st.number_input(\"Objectivity (w2)\", value=default_weights[1], format=\"%.3f\")\n",
    "            w3 = st.number_input(\"Measurability (w3)\", value=default_weights[2], format=\"%.3f\")\n",
    "        \n",
    "        with col2:\n",
    "            w4 = st.number_input(\"Distinctiveness (w4)\", value=default_weights[3], format=\"%.3f\")\n",
    "            w5 = st.number_input(\"Parsimony (w5)\", value=default_weights[4], format=\"%.3f\")\n",
    "            w6 = st.number_input(\"Sensitivity (w6)\", value=default_weights[5], format=\"%.3f\")\n",
    "        \n",
    "        with col3:\n",
    "            w7 = st.number_input(\"Cost-effectiveness (w7)\", value=default_weights[6], format=\"%.3f\")\n",
    "            w8 = st.number_input(\"Alignment (w8)\", value=default_weights[7], format=\"%.3f\")\n",
    "            w9 = st.number_input(\"Cognitive Coherence (w9)\", value=default_weights[8], format=\"%.3f\")\n",
    "        \n",
    "        total = w1 + w2 + w3 + w4 + w5 + w6 + w7 + w8 + w9\n",
    "        \n",
    "        if abs(total - 1.0) < 0.001:\n",
    "            st.success(f\"✅ Sum: {total:.3f}\")\n",
    "        else:\n",
    "            st.error(f\"❌ Sum: {total:.3f} (must equal 1.0)\")\n",
    "        \n",
    "        if st.button(\"🚀 Run Optimization\", use_container_width=True):\n",
    "            if abs(total - 1.0) >= 0.001:\n",
    "                st.error(\"⚠️ Weights must sum to 1.0\")\n",
    "                return\n",
    "            \n",
    "            with st.spinner(\"Running optimization...\"):\n",
    "                try:\n",
    "                    weights = {\n",
    "                        'w1': w1, 'w2': w2, 'w3': w3,\n",
    "                        'w4': w4, 'w5': w5, 'w6': w6,\n",
    "                        'w7': w7, 'w8': w8, 'w9': w9\n",
    "                    }\n",
    "                    \n",
    "                    opt_result, error = build_optimization_model_with_weights(results, weights)\n",
    "                    \n",
    "                    if error:\n",
    "                        st.error(f\"Optimization failed: {error}\")\n",
    "                        return\n",
    "                    \n",
    "                    st.session_state.opt_result = opt_result\n",
    "                    \n",
    "                    st.success(\"✅ Optimization completed successfully!\")\n",
    "                    \n",
    "                    col1, col2, col3 = st.columns(3)\n",
    "                    with col1:\n",
    "                        st.metric(\"Status\", opt_result['status'].upper())\n",
    "                    with col2:\n",
    "                        st.metric(\"Selected Criteria\", int(opt_result['n_value']))\n",
    "                    with col3:\n",
    "                        st.metric(\"Objective Value\", f\"{opt_result['obj_value']:.4f}\")\n",
    "                    \n",
    "                    st.subheader(\"✅ Selected Criteria\")\n",
    "                    for i, crit in enumerate(opt_result['selected'], 1):\n",
    "                        idx = results['criteria_ids'].index(crit)\n",
    "                        if idx < len(results['criteria_names']):\n",
    "                            name = results['criteria_names'][idx]\n",
    "                            st.write(f\"{i}. **{crit}**: {name}\")\n",
    "                    \n",
    "                    st.subheader(\"❌ Not Selected\")\n",
    "                    for crit in opt_result['not_selected']:\n",
    "                        idx = results['criteria_ids'].index(crit)\n",
    "                        reason = \"Below threshold\" if crit in opt_result['excluded'] else \"Not optimal\"\n",
    "                        if idx < len(results['criteria_names']):\n",
    "                            name = results['criteria_names'][idx]\n",
    "                            st.write(f\"• **{crit}**: {name} ({reason})\")\n",
    "                \n",
    "                except Exception as e:\n",
    "                    st.error(f\"Error: {str(e)}\")\n",
    "    \n",
    "    # ============================================================\n",
    "    # PAGE 4: RESULTS\n",
    "    # ============================================================\n",
    "    elif page == \"📈 Results\":\n",
    "        st.header(\"📈 Results Summary\")\n",
    "        \n",
    "        if st.session_state.results is None or st.session_state.opt_result is None:\n",
    "            st.warning(\"⚠️ Please process data and run optimization first!\")\n",
    "            return\n",
    "        \n",
    "        results = st.session_state.results\n",
    "        opt_result = st.session_state.opt_result\n",
    "        \n",
    "        # Generate report\n",
    "        report = f\"\"\"============================================================\n",
    "CRITERIA SELECTION DASHBOARD - COMPLETE RESULTS SUMMARY\n",
    "============================================================\n",
    "\n",
    "📊 DATA SUMMARY\n",
    "----------------------------------------\n",
    "Total Criteria Evaluated: {results['num_criteria']}\n",
    "Total Alternatives: {results['num_alternatives']}\n",
    "Number of Experts: {results['num_experts']}\n",
    "\n",
    "🎯 OPTIMIZATION RESULTS\n",
    "----------------------------------------\n",
    "Optimization Status: {opt_result['status'].upper()}\n",
    "Objective Function Value: {opt_result['obj_value']:.6f}\n",
    "Selected Criteria Count: {int(opt_result['n_value'])}\n",
    "Objectivity Ratio: {opt_result['rho_value']:.4f}\n",
    "\n",
    "✅ SELECTED CRITERIA\n",
    "----------------------------------------\n",
    "\"\"\"\n",
    "        \n",
    "        for i, crit in enumerate(opt_result['selected'], 1):\n",
    "            idx = results['criteria_ids'].index(crit)\n",
    "            if idx < len(results['criteria_names']):\n",
    "                name = results['criteria_names'][idx]\n",
    "                report += f\"{i}. {crit}: {name}\\n\"\n",
    "        \n",
    "        report += \"\\n❌ EXCLUDED/NOT SELECTED CRITERIA\\n\"\n",
    "        report += \"-\" * 40 + \"\\n\"\n",
    "        \n",
    "        for crit in opt_result['not_selected']:\n",
    "            idx = results['criteria_ids'].index(crit)\n",
    "            reason = \"Below threshold\" if crit in opt_result['excluded'] else \"Not optimal\"\n",
    "            if idx < len(results['criteria_names']):\n",
    "                name = results['criteria_names'][idx]\n",
    "                report += f\"• {crit}: {name} ({reason})\\n\"\n",
    "        \n",
    "        # Display metrics\n",
    "        selected_indices = [i-1 for i, val in enumerate(opt_result['binary']) if val == 1]\n",
    "        \n",
    "        if selected_indices:\n",
    "            st.subheader(\"📈 Performance Metrics\")\n",
    "            col1, col2, col3, col4 = st.columns(4)\n",
    "            \n",
    "            if results['c_values'] is not None:\n",
    "                avg_completeness = np.mean([results['c_values'][i] for i in selected_indices])\n",
    "                col1.metric(\"Avg Completeness\", f\"{avg_completeness:.2f}/10\")\n",
    "            \n",
    "            if results['m_values'] is not None:\n",
    "                avg_measurability = np.mean([results['m_values'][i] for i in selected_indices])\n",
    "                col2.metric(\"Avg Measurability\", f\"{avg_measurability:.2f}/10\")\n",
    "            \n",
    "            if results['a_values'] is not None:\n",
    "                avg_alignment = np.mean([results['a_values'][i] for i in selected_indices])\n",
    "                col3.metric(\"Avg Alignment\", f\"{avg_alignment:.2f}/10\")\n",
    "            \n",
    "            if results['cc_values'] is not None:\n",
    "                avg_cognitive = np.mean([results['cc_values'][i] for i in selected_indices])\n",
    "                col4.metric(\"Avg Cognitive\", f\"{avg_cognitive:.2f}/10\")\n",
    "        \n",
    "        # Display report\n",
    "        st.text_area(\"Full Report\", report, height=400)\n",
    "        \n",
    "        # Download button\n",
    "        st.download_button(\n",
    "            label=\"📄 Download Report\",\n",
    "            data=report,\n",
    "            file_name=f\"MCDM_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt\",\n",
    "            mime=\"text/plain\",\n",
    "            use_container_width=True\n",
    "        )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9696e23-a323-4510-aad1-9f83f3234e6a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
